name: etapa2
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.4.0 # api consume
  retrofit: '>=4.0.3 <5.0.0' # api consume
  json_annotation: 4.9.0 # json annotation

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  retrofit_generator: ^8.1.0 # generator code from api
  build_runner: any  # generator code
  json_serializable: ^6.7.1  # generator code
