name: package_fake_api_store
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  http: ^1.2.2 # api consume
  dartz: ^0.10.1 # functional programming

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
